
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int DIVISOR = 37;
  public static final int EQUALS = 30;
  public static final int INTEGER = 45;
  public static final int CLOSE_KEYS = 24;
  public static final int GREATER = 34;
  public static final int INT = 7;
  public static final int OPEN_KEYS = 23;
  public static final int LESS = 32;
  public static final int MINUS = 26;
  public static final int STATIC = 5;
  public static final int SEMICOLON = 15;
  public static final int AND = 29;
  public static final int OR = 28;
  public static final int COMMA = 17;
  public static final int CLASS = 4;
  public static final int LESS_EQUAL = 33;
  public static final int MULTIPLY = 36;
  public static final int PLUS = 25;
  public static final int MAIN = 41;
  public static final int EXCLAMATION = 38;
  public static final int ASSIGN = 18;
  public static final int IF = 10;
  public static final int THIS = 12;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int RETURN = 9;
  public static final int OPEN_BRACK = 21;
  public static final int CLOSE_PARENT = 20;
  public static final int TRUE = 44;
  public static final int GREATER_EQUAL = 35;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int PERCENT = 27;
  public static final int VOID = 6;
  public static final int OPEN_PARENT = 19;
  public static final int ELSE = 11;
  public static final int POINT = 16;
  public static final int WHILE = 14;
  public static final int PUBLIC = 2;
  public static final int CLOSE_BRACK = 22;
  public static final int EXTENDS = 3;
  public static final int SYSO = 40;
  public static final int STRING = 39;
  public static final int DIFF = 31;
  public static final int FALSE = 43;
  public static final int LENGTH = 42;
  public static final int IDENTIFIER = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "EXTENDS",
  "CLASS",
  "STATIC",
  "VOID",
  "INT",
  "BOOLEAN",
  "RETURN",
  "IF",
  "ELSE",
  "THIS",
  "NEW",
  "WHILE",
  "SEMICOLON",
  "POINT",
  "COMMA",
  "ASSIGN",
  "OPEN_PARENT",
  "CLOSE_PARENT",
  "OPEN_BRACK",
  "CLOSE_BRACK",
  "OPEN_KEYS",
  "CLOSE_KEYS",
  "PLUS",
  "MINUS",
  "PERCENT",
  "OR",
  "AND",
  "EQUALS",
  "DIFF",
  "LESS",
  "LESS_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "MULTIPLY",
  "DIVISOR",
  "EXCLAMATION",
  "STRING",
  "SYSO",
  "MAIN",
  "LENGTH",
  "FALSE",
  "TRUE",
  "INTEGER",
  "IDENTIFIER"
  };
}

